Rename all instances of osg and styleguide
oslokommune/ukeweb_designsystem pull request #438
Opened 2023-09-08 09:07 UTC by jonaashl

Lykke til 🫶👹

2023-09-11 08:23 UTC, larsboldt requested changes

2023-09-11 08:23 UTC, larsboldt commented on .github/workflows/release.yml
> +      URL: 'Designsystem Devtools'
Oslo Designsystem

2023-09-11 08:23 UTC, larsboldt commented on .github/workflows/test.yml
> +      URL: 'Designsystem Devtools'
Oslo Designsystem

2023-09-11 08:23 UTC, larsboldt commented on .gitignore
> +.devbox/project.*
Ta bort denne linja og /* på linja over

2023-09-11 08:23 UTC, larsboldt commented on README.md
> +![Oslo Designsystem Banner](./src/assets/images/Facebook1.jpg)
Facebook1?

2023-09-11 08:23 UTC, larsboldt commented on README.md
> +<h1 align="center">Oslo Designsystem 🎨 🧑‍🎨</h1>
Ingen ikoner

2023-09-11 08:23 UTC, larsboldt commented on README.md
> +## Installation 🚀
Ikon foran eller bak?

2023-09-11 08:23 UTC, larsboldt commented on README.md
> +module.exports = {
er dette testet?

2023-09-11 08:23 UTC, larsboldt commented on README.md
> +Browse the Designsystem for components and add the code to your project.
ta bort "the", bruk Oslo Designsystem

2023-09-11 08:23 UTC, larsboldt commented on README.md
> +Slack: beepbeepboopboop
beep?

2023-09-11 12:26 UTC, larsboldt requested changes

2023-09-11 12:26 UTC, larsboldt commented on README.md
> +![Oslo Designsystem Banner](./src/assets/images/oslo-header-placeholder.jpg)
oslo-header er fint, fjern placeholder

2023-09-12 08:48 UTC, larsboldt requested changes

2023-09-12 08:48 UTC, larsboldt commented on README.md
> +## 📚 Table of Content
Table of Contents - s på slutten

2023-09-12 12:35 UTC, jonaashl commented on README.md
> +Slack: beepbeepboopboop
Venter fortsatt på avklaring om hvilken slack kanal og e-post som skal brukes

2023-09-12 13:58 UTC, kbergha approved these changes
Vondt i scrolle-finger'n!

2023-09-13 07:13 UTC, cristain7 approved these changes

2023-09-13 09:34 UTC, jonaashl commented on README.md
> +module.exports = {
Usage er nå fjernet fra readme

2023-09-13 10:51 UTC, larsboldt approved these changes

2023-09-14 09:11 UTC, merged