Io 1043 Accordion component
oslokommune/ukeweb_designsystem pull request #448
Opened 2023-09-21 12:38 UTC by cristain7

2023-09-22 07:10 UTC, kbergha commented on src/components/accordion/accordion.scss
> +    background-color: white;
Ikke `colors.$white`? (gjelder også linje 53 + 59 + 76 + 109)

2023-09-22 07:12 UTC, kbergha commented on src/general/helpers/collapsible/collapsible.init.js
> +import OsgCollapsible from './collapsible';
Osg? Er det ikke Ods nå (også linje 4)?

2023-09-22 07:21 UTC, cristain7 commented on src/components/accordion/accordion.scss
> +    background-color: white;
Oppdatert!

2023-09-22 07:22 UTC, cristain7 commented on src/general/helpers/collapsible/collapsible.init.js
> +import OsgCollapsible from './collapsible';
Oppdatert det!

2023-09-22 07:30 UTC, kbergha reviewed
Siden dette er et nytt komponent, er det testet på flere enheter og nettlesere for rariteter?

2023-09-22 09:00 UTC, larsboldt requested changes

2023-09-22 09:00 UTC, larsboldt commented on src/general/helpers/collapsible/collapsible.html
> +<div class="ods-devtools-nondevmode">
There should be examples of all options in developer tab so its easy to see that the code is working

2023-09-22 09:00 UTC, larsboldt commented on src/general/helpers/collapsible/collapsible.js
> +    window.addEventListener('OsgBreakpointChange', handleBreakpointChange);
ods

2023-09-22 09:00 UTC, larsboldt commented on src/general/helpers/collapsible/collapsible.js
> +    window.removeEventListener('OsgBreakpointChange', handleBreakpointChange);
ods

2023-09-22 09:00 UTC, larsboldt commented on src/general/helpers/collapsible/collapsible.init.js
> +  OsgCollapsible.init();
ods

2023-09-22 11:11 UTC, cristain7 commented on src/components/accordion/accordion.json
> +  "version": "1.1",
Absolutt 1.0!

2023-09-22 12:44 UTC, cristain7 commented
> Siden dette er et nytt komponent, er det testet på flere enheter og nettlesere for rariteter?

@kbergha jeg har testet i flere nettlesere og mobil

2023-09-22 13:47 UTC, kbergha approved these changes

2023-09-25 07:49 UTC, larsboldt requested changes

2023-09-25 07:49 UTC, larsboldt commented on src/general/helpers/collapsible/collapsible.init.js
> +  OsdCollapsible.init();
Osd? Ods...

2023-09-25 07:49 UTC, larsboldt commented on src/general/helpers/collapsible/collapsible.js
> +  if (e.target.classList.contains('ods-animate')) {
what is ods-animate and ods-rotate?

2023-09-25 07:49 UTC, larsboldt commented on src/components/accordion/accordion.scss
> +    @extend %ods-padding-top-6-breakpoint-large,  %ods-padding-bottom-8-breakpoint-large, %ods-padding-horizontal-8-breakpoint-large;
remove extra space

2023-09-25 08:03 UTC, cristain7 commented on src/general/helpers/collapsible/collapsible.js
> +  if (e.target.classList.contains('ods-animate')) {
ods-animate is a class flag to run animation or not.
ods-rotate is the class of the animation that rotates the arrow.

2023-09-25 08:14 UTC, larsboldt commented on src/general/helpers/collapsible/collapsible.js
> +  if (e.target.classList.contains('ods-animate')) {
But why are they not part of the pull request? Is this a new system that we have implemented or is it already in designsystem?

2023-09-25 08:16 UTC, cristain7 commented on src/general/helpers/collapsible/collapsible.js
> +  if (e.target.classList.contains('ods-animate')) {
They should be! Will check what happened here

2023-09-25 08:28 UTC, cristain7 commented on src/general/helpers/collapsible/collapsible.js
> +  if (e.target.classList.contains('ods-animate')) {
ods-animate and ods-rotate are part of this review, they are used only in this function handleAnimation(e)

2023-09-25 08:32 UTC, larsboldt commented on src/general/helpers/collapsible/collapsible.js
> +  if (e.target.classList.contains('ods-animate')) {
I don't get it - where is the css for ods-rotate defined?

2023-09-25 08:35 UTC, larsboldt commented on src/general/helpers/collapsible/collapsible.js
> +  if (e.target.classList.contains('ods-animate')) {
What is the concept behind ods-animate, where is it documented? A generic name like this must refer to a system documented somewhere?

2023-09-25 08:37 UTC, cristain7 commented on src/general/helpers/collapsible/collapsible.js
> +  if (e.target.classList.contains('ods-animate')) {
Good point! It is part of the collapsible helper and should be documented there.
Also ods-rotate is defined i accordion (wrooooong) that's why you didn't find it. Will move it to helper

2023-09-25 12:46 UTC, larsboldt commented on src/general/helpers/collapsible/collapsible.scss
> +.ods-collapsible__trigger::after {
Have you checked that this does not affect any current triggers?

2023-09-25 12:47 UTC, cristain7 commented on src/general/helpers/collapsible/collapsible.scss
> +.ods-collapsible__trigger::after {
It is the only place using this class name

2023-09-25 12:49 UTC, cristain7 commented on src/general/helpers/collapsible/collapsible.scss
> +.ods-collapsible__trigger::after {
I didn't mean to add this file

2023-09-25 12:50 UTC, larsboldt commented on src/general/helpers/collapsible/collapsible.scss
> +.ods-collapsible__trigger::after {
Isn't this related to rotate, should not the classname reflect that?

2023-09-25 12:54 UTC, cristain7 commented on src/general/helpers/collapsible/collapsible.scss
> +.ods-collapsible__trigger::after {
The purpose of removing the animation functionality from the accordion component is to create an animation helper. So it shouldn't be on the collapsible helper either.

2023-09-25 13:21 UTC, cristain7 commented on src/general/helpers/collapsible/collapsible.scss
> +.ods-collapsible__trigger::after {
I removed this file

2023-09-25 13:28 UTC, larsboldt approved these changes

2023-09-25 13:37 UTC, merged