Fix BEM format and issue in the developer tab of input counter
oslokommune/ukeweb_designsystem pull request #449
Opened 2023-09-21 12:56 UTC by cristain7

2023-09-22 07:20 UTC, larsboldt requested changes

2023-09-22 07:20 UTC, larsboldt commented on src/components/form/input/input.scss
> +    @extend %ods-text--size-juliett;
Did this pass the linter? All @extends should be at the top

2023-09-22 07:20 UTC, larsboldt commented on src/components/form/input/input.js
> +const OdsInput = {
Missing the single element bindings making this hard to use in a vue context

2023-09-22 07:25 UTC, cristain7 commented on src/components/form/input/input.scss
> +    @extend %ods-text--size-juliett;
it did, because it is in the test environment

2023-09-22 11:34 UTC, cristain7 commented on src/components/form/input/input.scss
> +    @extend %ods-text--size-juliett;
Fixed all the  linting

2023-09-22 11:34 UTC, cristain7 commented on src/components/form/input/input.js
> +const OdsInput = {
Added it

2023-09-22 13:46 UTC, kbergha approved these changes

2023-09-25 07:59 UTC, larsboldt requested changes

2023-09-25 07:59 UTC, larsboldt commented on src/components/form/input/input.js
> +    triggerChangeNumber((item) => {
endres til triggerIterator for å være konsistent med de andre komponentene

2023-09-25 07:59 UTC, larsboldt commented on src/components/form/input/input.js
> +    triggerChangeNumber((item) => {
endres til triggerIterator for å være konsistent med de andre komponentene

2023-09-25 13:31 UTC, larsboldt approved these changes

2023-09-25 13:38 UTC, merged