Io 1091 Refactor grid so classes are generated properly
oslokommune/ukeweb_designsystem pull request #457
Opened 2023-10-13 08:05 UTC by cristain7

2023-10-16 13:06 UTC, larsboldt commented
Is this problem something that was introduced in the 1.0 release? If not, why did this problem arise now?

2023-10-17 13:21 UTC, larsboldt requested changes

2023-10-17 13:21 UTC, larsboldt commented on CHANGELOG.md
> +## [unreleased]
Unreleased, uppercase U

2023-10-17 13:21 UTC, larsboldt commented on src/general/grid/grid.scss
> +    &-breakpoint-medium {
By moving these &--gap is left out of the fun

2023-10-18 08:12 UTC, cristain7 commented on src/general/grid/grid.scss
> +    &-breakpoint-medium {
I did a little test to see what the outcomes of extending the class was, and seems like &--gap wasn't part of the fun either.
I didn't find on the previous styleguide css file any of these classes:
.osg-grid--gap-breakpoint-medium, 
.osg-grid--gap-breakpoint-large,
.osg-grid--gap-large

Probably that was a bug.

It only applied the styles that didn't belong to a nested selector, and didn't generate subclasses on the class that extended it.

Therefore, there aren't breaking changes here.

2023-10-19 09:12 UTC, cristain7 commented on src/general/grid/grid.scss
> +    &-breakpoint-medium {
Classes generated on production vs classes generated on designsystem test environment are the same:

PRODUCTION (oslo.kommune.no):

`
.ods-grid--gap,.ods-grid--gap-column {
    column-gap: 1rem
}

.ods-grid--gap,.ods-grid--gap-row {
    row-gap: 1rem
}

.ods-grid--gap-row-large {
    row-gap: 2rem
}

@media screen and (min-width: 769px) {
    .ods-grid--gap,.ods-grid--gap-column {
        column-gap:2rem
    }
}

@media screen and (min-width: 769px) {
    .ods-grid--gap,.ods-grid--gap-row {
        row-gap:2rem
    }
}

@media screen and (min-width: 769px) {
    .ods-grid--gap-column-breakpoint-medium {
        column-gap:2rem
    }
}

@media screen and (min-width: 1024px) {
    .ods-grid--gap-column-breakpoint-large {
        column-gap:2rem
    }
}

@media screen and (min-width: 769px) {
    .ods-grid--gap-row-breakpoint-medium {
        row-gap:2rem
    }
}

@media screen and (min-width: 1024px) {
    .ods-grid--gap-row-breakpoint-large {
        row-gap:2rem
    }
}

@media screen and (min-width: 769px) {
    .ods-grid--gap-row-large {
        row-gap:3.25rem
    }
}

@media screen and (min-width: 769px) {
    .ods-grid--gap-row-large-breakpoint-medium {
        row-gap:3.25rem
    }
}

@media screen and (min-width: 1024px) {
    .ods-grid--gap-row-large-breakpoint-large {
        row-gap:3.25rem
    }
}
`

DESIGNSYSTEM (test.designsystem.io)
`
.osg-grid--gap-column,.osg-grid--gap {
    column-gap: 1rem
}

.osg-grid--gap-row,.osg-grid--gap {
    row-gap: 1rem
}

.osg-grid--gap-row-large {
    row-gap: 2rem
}

@media screen and (min-width: 769px) {
    .osg-grid--gap-column,.osg-grid--gap {
        column-gap:2rem
    }
}

@media screen and (min-width: 769px) {
    .osg-grid--gap-column-breakpoint-medium {
        column-gap:2rem
    }
}

@media screen and (min-width: 1024px) {
    .osg-grid--gap-column-breakpoint-large {
        column-gap:2rem
    }
}

@media screen and (min-width: 769px) {
    .osg-grid--gap-row,.osg-grid--gap {
        row-gap:2rem
    }
}

@media screen and (min-width: 769px) {
    .osg-grid--gap-row-breakpoint-medium {
        row-gap:2rem
    }
}

@media screen and (min-width: 1024px) {
    .osg-grid--gap-row-breakpoint-large {
        row-gap:2rem
    }
}

@media screen and (min-width: 769px) {
    .osg-grid--gap-row-large {
        row-gap:3.25rem
    }
}

@media screen and (min-width: 769px) {
    .osg-grid--gap-row-large-breakpoint-medium {
        row-gap:3.25rem
    }
}

@media screen and (min-width: 1024px) {
    .osg-grid--gap-row-large-breakpoint-large {
        row-gap:3.25rem
    }
}
`

2023-10-20 07:47 UTC, closed without merging