Io 160 - change styles on datapicker component
oslokommune/ukeweb_designsystem pull request #473
Opened 2023-11-07 09:13 UTC by jonaashl

This PR contains changes to font-type, scaling, spacing and state/colours. (originally just font-size issues)

The display of date-input fields are also tweaked, since they should never be 100% width

2023-11-08 08:09 UTC, kbergha commented on src/components/form/date/date.html
> +                  <input type="text" class="ods-date__input" autocomplete="off" placeholder="dd/mm/yyyy" />
Mens du allerede holder på her, kan vi fikse placeholder til å være dd.mm.yyyy ?
Så blir det riktigere mtp. skriveregler...

(gjelder også linje 34)

2023-11-08 08:35 UTC, cristain7 commented on src/components/form/date/date.html
> +          <div class="ods-grid">
Mangles denne grid i Developer tab

2023-11-08 08:39 UTC, cristain7 commented on src/components/form/date/date.scss
>          right: 5px;
0.3 rem

2023-11-08 08:39 UTC, cristain7 commented on src/components/form/date/date.scss
>          left: 5px;
0.3 rem

2023-11-08 08:51 UTC, cristain7 commented
![Screenshot 2023-11-08 at 09 48 21](https://github.com/oslokommune/ukeweb_designsystem/assets/37497176/40c69e11-5a1a-46d4-a95a-d79198b457ba)
Hover over disse knappene ser litt off

2023-11-08 09:41 UTC, larsboldt requested changes

2023-11-08 09:41 UTC, larsboldt commented on src/components/form/date/date.html
> +          <div class="ods-grid">
Nå er grid en del av kodeeksempelet i View code i devtools, den skal den ikke være, flytt grid ett nivå opp så uteblir den.

2023-11-08 09:41 UTC, larsboldt commented on src/components/form/date/date.html
> +          <div class="ods-grid">
Nå er grid en del av kodeeksempelet i View code i devtools, den skal den ikke være, flytt grid ett nivå opp så uteblir den.

2023-11-08 09:41 UTC, larsboldt commented on src/components/form/date/date.html
> +          <div class="ods-grid">
Nå er grid en del av kodeeksempelet i View code i devtools, den skal den ikke være, flytt grid ett nivå opp så uteblir den.

2023-11-08 12:17 UTC, jonaashl commented on src/components/form/date/date.html
> +          <div class="ods-grid">
Da vil jo også den kode-boxen bli påvirket av grid, er dette ønskelig?
Den øverste er med grid flyttet ut av kodeboksen

<img width="1114" alt="image" src="https://github.com/oslokommune/ukeweb_designsystem/assets/49975790/55244b4c-bc2d-44fa-ad2b-b12534184643">

2023-11-13 10:03 UTC, cristain7 submitted a review, later dismissed

2023-11-14 12:47 UTC, larsboldt requested changes

2023-11-14 12:47 UTC, larsboldt commented on src/components/form/date/date.scss
>              // font-size: typography.$size-14;
Ingen utkommentert kode

2023-11-14 12:47 UTC, larsboldt commented on src/components/form/date/date.html
> +          <div class="ods-grid">
Ser fortsatt grid i testmiljøet - er det ikke oppdatert?

2023-11-20 09:19 UTC, larsboldt approved these changes

2023-11-20 10:14 UTC, cristain7 approved these changes

2023-11-21 09:08 UTC, kbergha approved these changes

2023-11-23 10:51 UTC, kbergha commented
Antar at denne skal lukkes, og at #479 har tatt over?

2023-11-24 07:50 UTC, closed without merging