fix bug causing wrong colours on search season
oslokommune/ukeweb_designsystem pull request #481
Opened 2023-12-04 11:00 UTC by jonaashl

2023-12-04 11:47 UTC, jonaashl commented
Lager en PR så det kommer med 1.1 releasen. Vet ikke helt hvordan og om det kommer til å påvirke lars sin haste-fiks

2023-12-05 08:27 UTC, larsboldt requested changes

2023-12-05 08:27 UTC, larsboldt commented on src/components/form/search_seasons/search_seasons.scss
> +  &--blue-dark {
ett linjeskift for mye på linje 252/253

2023-12-05 08:27 UTC, larsboldt commented on CHANGELOG.md
> +- Fixed wrong colours on search-seasons
Hmm... tenker kanskje mer ordlyden er: Fixed wrong scope for modifiers blue-dark and green-dark which caused them not working as intended --- eller noe i den duren

2023-12-05 13:59 UTC, larsboldt approved these changes

2023-12-11 07:00 UTC, kbergha approved these changes

2023-12-11 07:34 UTC, cristain7 commented on CHANGELOG.md
> +- Fixed a scope issue where blue-dark and green-dark modifiers in search-season did not receive the correct styling.
Jeg vil ikke være kresen, men komponenten heter "Search seasons" ikke search-season :)

2023-12-11 07:56 UTC, cristain7 approved these changes

2023-12-11 10:15 UTC, larsboldt approved these changes

2023-12-11 12:04 UTC, merged