Add new width and height classes
oslokommune/ukeweb_designsystem pull request #484
Opened 2023-12-21 14:11 UTC by jonaashl

Litt usikker på hvordan jeg skal dokumentere utenom å sette opp i en tabell. Skal vi vise brukseksempler?

2024-02-06 14:03 UTC, jonaashl commented
![](https://github.trello.services/images/mini-trello-icon.png) [Visibility](https://trello.com/c/1MOaQzjs/1188-visibility)

2024-03-21 07:07 UTC, larsboldt requested changes

2024-03-21 07:07 UTC, larsboldt commented on CHANGELOG.md
> +- Added new classes for width and height.
?

2024-04-04 07:52 UTC, cristain7 commented
> Litt usikker på hvordan jeg skal dokumentere utenom å sette opp i en tabell. Skal vi vise brukseksempler?

Jeg tenker på de bør være i en annen hjelper som "Size" eller "Dimension" og flytte hele "Heigh and width" seksjonen der.

2024-04-09 07:33 UTC, larsboldt submitted a review, later dismissed

2024-04-09 07:37 UTC, kbergha submitted a review, later dismissed
Koden ser fin ut, men ta en runde på det med dok som nevnt fra tidligere.

2024-04-30 07:27 UTC, cristain7 commented on src/general/helpers/height_and_width/height_and_width.json
> +  "preset": "clean"
`"tags": ["height", "width"]`

2024-05-02 13:33 UTC, cristain7 requested changes
Du må inkludere height_and_width SCSS filen i src/general/_index.scss

2024-05-03 07:50 UTC, cristain7 submitted a review, later dismissed

2024-05-03 07:52 UTC, cristain7 commented on CHANGELOG.md
> +- Fixed an issue where long links would not break properly.
Fjern det

2024-05-03 07:53 UTC, cristain7 commented on CHANGELOG.md
> -### Changed
ok, dette må fikses :)

2024-05-03 08:04 UTC, cristain7 commented on CHANGELOG.md
> -### Changed
changelog i main branchen har duplisert 'fixed' seksjon, når dette merges til main vil fiks det.

2024-05-06 17:45 UTC, larsboldt commented on src/general/_index.scss
> +@use "helpers/height_and_width/height_and_width";
rename til width_and_height, x og y er normal rekkefølge

2024-05-06 17:47 UTC, larsboldt commented on src/general/helpers/height_and_width/height_and_width.scss
> +@each $width, $value in $widths {
bør vi ha brekkpunkter også? mest sannsynlig

2024-05-06 17:48 UTC, larsboldt commented on src/general/helpers/height_and_width/height_and_width.scss
> +@each $height, $value in $heights {
bør vi ha brekkpunkter også? mest sannsynlig

2024-05-07 07:56 UTC, jonaashl commented on src/general/helpers/height_and_width/height_and_width.scss
> +$heights: (
<img width="532" alt="image" src="https://github.com/oslokommune/ukeweb_designsystem/assets/49975790/173b942a-7e41-4ab5-9bd2-bed044e1847c">

legger ved bilde fra ratio.scss

Det skal ikke være space her da lintereglene våre ikke tillater tom linje før $-variabel
https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/dollar-variable-empty-line-before

2024-05-07 08:05 UTC, jonaashl commented on src/general/helpers/height_and_width/height_and_width.scss
> +@each $height, $value in $heights {
Har lagt til brekkpunkter! Ta en sjekk

2024-05-07 08:06 UTC, jonaashl commented on src/general/_index.scss
> +@use "helpers/height_and_width/height_and_width";
👍

2024-05-07 09:48 UTC, larsboldt approved these changes

2024-05-07 09:52 UTC, cristain7 approved these changes

2024-05-07 10:01 UTC, kbergha approved these changes

2024-05-07 10:05 UTC, merged