io-1106 - Heading skal være en del av accordion
oslokommune/ukeweb_designsystem pull request #485
Opened 2023-12-27 09:55 UTC by jonaashl

2024-02-06 14:03 UTC, jonaashl commented
![](https://github.trello.services/images/mini-trello-icon.png) [Accordion - Heading skal være en del av ods-accordion](https://trello.com/c/LKBlyxwv/1106-accordion-heading-skal-v%C3%A6re-en-del-av-ods-accordion)

2024-03-13 10:21 UTC, cristain7 submitted a review, later dismissed

2024-03-21 07:07 UTC, larsboldt requested changes

2024-03-21 07:07 UTC, larsboldt commented on CHANGELOG.md
> +- Change structure of accordion component to follow BEM.
?

2024-04-04 08:02 UTC, cristain7 approved these changes

2024-04-09 07:23 UTC, larsboldt approved these changes

2024-04-09 07:34 UTC, kbergha approved these changes
Blir dette da per def. en breaking change?

2024-04-09 07:38 UTC, cristain7 commented
> Blir dette da per def. en breaking change?

Nei, heading er implementert inne komponenten i internet prosjekt. Det bare trenger å oppdaterer det her

2024-04-17 11:56 UTC, cristain7 approved these changes

2024-05-06 17:48 UTC, larsboldt approved these changes

2024-05-07 10:05 UTC, merged