Io 1186 - add truncated and nowrap
oslokommune/ukeweb_designsystem pull request #486
Opened 2024-01-05 08:56 UTC by jonaashl

2024-02-06 14:04 UTC, jonaashl commented
![](https://github.trello.services/images/mini-trello-icon.png) [Typography](https://trello.com/c/1NxPov4C/1186-typography)

2024-03-13 10:52 UTC, cristain7 commented on src/general/typography/typography.html
> +    <p>Be careful when truncating text as the accessibility is limited. Truncation may cause issues with accessibility tools like screen readers.</p>
Jeg tenker at du kan slett de siste setningen.
NVDA, JAWS og VoiceOver støtter truncate tekst med ellipsis. 
Her du kan test eksempel:
https://butterpep.com/line-clamp-overflow-ellipsis.html
UU problemet kan være med overlappende tekst.

2024-04-09 07:32 UTC, kbergha approved these changes

2024-04-30 17:56 UTC, kbergha approved these changes

2024-05-03 07:47 UTC, cristain7 commented on src/system/_typography.scss
> +}
du kan unngå to iterasjoner over $modifiers ved å sette alle breakpointer på samme loop:

```
@each $name, $values in $modifiers {
  %ods-text--modifier-#{$name} {
    @include modifier($name);
  }

  %ods-text--modifier-#{$name}-breakpoint-medium {
    @include breakpoints.medium {
      @include modifier($name);
    }
  }

  %ods-text--modifier-#{$name}-breakpoint-large {
    @include breakpoints.large {
      @include modifier($name);
    }
  }
}
```

2024-05-06 17:52 UTC, larsboldt requested changes

2024-05-06 17:52 UTC, larsboldt commented on src/general/typography/typography.scss
> +  .ods-text--modifier-#{$name} {
Hvor kommer "modifier" fra? Det er ikke noe vi har brukt i "modifiers" frem til nå

2024-05-06 17:52 UTC, larsboldt commented on src/system/_typography.scss
> +  %ods-text--modifier-#{$name} {
Hvor kommer "modifier" fra? Det er ikke noe vi har brukt i "modifiers" frem til nå

2024-05-07 08:43 UTC, jonaashl commented on src/general/typography/typography.scss
> +  .ods-text--modifier-#{$name} {
Det stemmer, vi har ikke hatt truncated og no-wrap som klasser før. Jeg lagde "modifiers" fordi jeg tenkte at da er det lettere å legge inn flere modifiers i fremtiden, samtidig som jeg følger måten vi har gjort det på alle de andre typografi klassene.

Jeg kan også bare spesifikt legge inn "truncated" og "nowrap"? Har prøvd å følge oppsettet vi allerede har på "align", "size", "weight" og "style".

2024-05-07 08:45 UTC, jonaashl commented on src/system/_typography.scss
> +}
Alle de andre bruker samme oppsett som meg, skal jeg endre det på "style" "weight" "size" og "alignment" også?

2024-05-07 08:59 UTC, larsboldt commented on src/general/typography/typography.scss
> +  .ods-text--modifier-#{$name} {
alt etter -- i BEM er modifiers, så man trenger ikke eksplisitt ordet, det er implisitt

2024-05-07 09:00 UTC, larsboldt commented on src/system/_typography.scss
> +}
tror ikke du skal endre det, pga måten sass transpileres på så kan man få spesificity problemer hvis de ikke ligger i egen løkke

2024-05-07 09:52 UTC, jonaashl commented on src/general/typography/typography.scss
> +  .ods-text--modifier-#{$name} {
Ahh, her er det nok en misforståelse. Jeg opprettet klassen $modifiers som inneholder truncated og no-wrap.

på samme måte som vi har:
`%ods-text--style-#{$name}-breakpoint-medium;`
la jeg til:
`%ods-text--modifier-#{$name}-breakpoint-medium;`

Kanskje jeg skal endre navn på "modifier" til noe annet.

2024-05-07 10:02 UTC, larsboldt commented on src/general/typography/typography.scss
> +  .ods-text--modifier-#{$name} {
bare ikke ha det? ods-text--no-wrap, ods-text--truncated etc

2024-05-07 11:30 UTC, jonaashl commented on src/general/typography/typography.scss
> +  .ods-text--modifier-#{$name} {
Det funker det og!

Men vil påpeke at alle typografi klassene har en "prefix" utenom truncated og no-wrap
```
%ods-text--size-#{$name}
%ods-text--weight-#{$name}
%ods-text--style-#{$name}
%ods-text--align-#{$name}
```
Utenom "modifiers":
`%ods-text--#{$name}`

2024-05-07 16:23 UTC, larsboldt requested changes

2024-05-07 16:23 UTC, larsboldt commented on src/general/typography/typography.scss
> +  .ods-text--modifier-#{$name}-breakpoint-medium {
modifier

2024-05-07 16:23 UTC, larsboldt commented on src/general/typography/typography.scss
> +  .ods-text--modifier-#{$name}-breakpoint-large {
modifier

2024-05-07 16:23 UTC, larsboldt commented on src/general/typography/typography.scss
> +  .ods-text--modifier-#{$name} {
modifier

2024-05-07 16:23 UTC, larsboldt commented on src/general/typography/typography.html
> +    <p>.ods-text--modifier-nowrap</p>
modifier

2024-05-07 16:23 UTC, larsboldt commented on src/general/typography/typography.html
> +    <p>.ods-text--modifier-nowrap-breakpoint-medium</p>
modifier

2024-05-07 16:23 UTC, larsboldt commented on src/general/typography/typography.html
> +    <p>.ods-text--modifier-nowrap-breakpoint-large</p>
modifier

2024-05-07 16:23 UTC, larsboldt commented on src/general/typography/typography.html
> +    <p>.ods-text--modifier-truncate</p>
modifier

2024-05-07 16:23 UTC, larsboldt commented on src/general/typography/typography.html
> +    <p>.ods-text--modifier-truncate-breakpoint-medium</p>
modifier

2024-05-07 16:23 UTC, larsboldt commented on src/general/typography/typography.html
> +    <p>.ods-text--modifier-truncate-breakpoint-large</p>
modifier

2024-05-08 08:51 UTC, jonaashl commented on src/general/typography/typography.scss
> +  .ods-text--modifier-#{$name}-breakpoint-medium {
Da skal alle "modifier" være borte

2024-05-08 08:59 UTC, cristain7 approved these changes

2024-05-08 09:06 UTC, larsboldt approved these changes

2024-05-08 09:10 UTC, kbergha approved these changes

2024-05-10 08:29 UTC, merged