Io-621: add keyboard functionality and error handling to datepicker
oslokommune/ukeweb_designsystem pull request #493
Opened 2024-02-16 08:52 UTC by jonaashl

2024-03-14 07:44 UTC, cristain7 commented on src/components/form/date/date.vue
> +      <input type="text" class="ods-date__input" placeholder="dd.mm.yyyy" :value="displayDate" autocomplete="off" v-on:focus="toggleDatepicker(true)" @keyup="handleKeyboardInput" />
Dette skulle ikke være et hardkodet strengt

2024-03-14 08:14 UTC, cristain7 requested changes

2024-03-14 08:14 UTC, cristain7 commented on src/components/form/date/date.vue
> +    <div class="ods-status-message ods-status-message--danger" v-if="isError">
role="alert"
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions
https://www.w3.org/WAI/ARIA/apg/patterns/alert/examples/alert/

2024-03-15 08:28 UTC, jonaashl commented on src/components/form/date/date.vue
> +      <input type="text" class="ods-date__input" placeholder="dd.mm.yyyy" :value="displayDate" autocomplete="off" v-on:focus="toggleDatepicker(true)" @keyup="handleKeyboardInput" />
Oki, jeg har fjernet den igjen!

2024-03-15 08:29 UTC, jonaashl commented on src/components/form/date/date.vue
> +      <h2 class="ods-status-message__heading"><span class="ods-status-message__icon ods-icon--error-hexa" aria-hidden="true"></span>{{ isError }}</h2>
Hmmm, gjorde det fordi Vue evaluerer en string som truthy, så jeg bare kombinerte det 🤪

Enig i at det kan være litt forvirrende, endret til hasError og errorMessage

2024-03-21 07:11 UTC, larsboldt requested changes

2024-03-21 07:11 UTC, larsboldt commented on CHANGELOG.md
> +- Added keyboard functionality to datepicker component and upgraded to newest version.
?

2024-03-21 10:00 UTC, jonaashl commented on CHANGELOG.md
> +- Added keyboard functionality to datepicker component and upgraded to newest version.
Vet ikke helt hvordan jeg fikk til den.. fixed!

2024-04-04 08:54 UTC, cristain7 commented on src/components/form/date/date.vue
> +      <input type="text" class="ods-date__input" placeholder="dd.mm.yyyy" :value="displayDate" autocomplete="off" v-on:focus="toggleDatepicker(true)" @keyup="handleKeyboardInput" />
Jeg mente ikke å fjerne den :)
Det kan være en streng

2024-04-08 07:09 UTC, kbergha submitted a review, later dismissed

2024-04-17 11:52 UTC, cristain7 commented on src/components/form/date/date.html
> +                  <ods-date :date="date" :display-date="displayDate" placeholder="dd.mm.yyyy" label="Pick a date" v-on:set="setDate" :min="minDate" :max="maxDate"></ods-date>
placeholder nå er dynamisk:
:placeholder="placeholder"

2024-04-24 09:32 UTC, larsboldt submitted a review, later dismissed

2024-04-24 10:01 UTC, cristain7 commented on src/components/form/date/date.vue
> +      if (event.key === 'Enter' || event.keyCode === 13) {
```
 if (event.key !== 'Enter' && event.keyCode !== 13) {
return;
}
```
dette unngår å kjøre unødvendig logikk hvis ingen av tastene trykkes

2024-04-24 11:38 UTC, cristain7 approved these changes

2024-04-30 11:38 UTC, jonaashl commented
min / max er props med en default verdi.
disse kan overstyres ved instansieringen av komponentet. Kan selv velge navn på hva de skal hete. Vi bruker minDate og maxDate for å readability og for å lett finne frem til hvor verdien kommer fra.

Jeg fjernet minFormatted og maxFormatted og bruker heller en forenklet versjon med "toLocaleDateString" med en utbytting av "/" for "." Grunnen til dette er skrivereglene for oslo kommune sitt nettsted. fjernet min/maxFormatted for readability.

2024-04-30 17:55 UTC, kbergha approved these changes

2024-05-02 05:35 UTC, cristain7 approved these changes

2024-05-02 11:16 UTC, merged