Io-627: Refactor links in portrait-card for better accessibility
oslokommune/ukeweb_designsystem pull request #494
Opened 2024-02-21 13:57 UTC by jonaashl

Case tuned out more complex than initially thought due to lack of JS. Had to add hover styles on the card itself, causing "no link cards" to have hover styles. added new nolink class as a possible solution, but cards are starting to get complicated. might be time to step back and take a look at the structure.

(needs discussing)

2024-03-21 07:05 UTC, larsboldt requested changes

2024-03-21 07:05 UTC, larsboldt commented on CHANGELOG.md
> +- Fixed spacing around links and buttons in portrait card on all breakpoints.
Denne ligger vel på feil sted?

2024-03-21 10:06 UTC, jonaashl commented on CHANGELOG.md
> +- Fixed spacing around links and buttons in portrait card on all breakpoints.
Gjenganger dette.. Stammer fra saker som ble startet på før 1.1 ble releaset.. også har det blitt kluss i changelogen

2024-04-08 07:08 UTC, kbergha approved these changes

2024-04-11 06:49 UTC, kbergha submitted a review, later dismissed

2024-04-15 13:05 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                Heading
"Heading" må være inne <a> element

2024-04-15 13:05 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                <a class="ods-portrait-card__link" href="javascript:void(0)"></a>
'Heading' må være inne <a> element

2024-04-15 13:05 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                Heading
'Heading' må være inne <a> element

2024-04-15 13:05 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                Heading
'Heading' må være inne <a> element

2024-04-15 13:05 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                Heading
'Heading' må være inne <a> element

2024-04-15 13:05 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                Heading
'Heading' må være inne <a> element

2024-04-15 13:06 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                    Heading
'Heading' må være inne <a> element

2024-04-15 13:06 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                    Heading
'Heading' må være inne <a> element

2024-04-15 13:07 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                    Heading
'Heading' må være inne <a> element

2024-04-15 13:07 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                    Heading
'Heading' må være inne <a> element

2024-04-15 13:07 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                    Heading
'Heading' må være inne <a> element

2024-04-15 13:07 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                    Heading
'Heading' må være inne <a> element

2024-04-15 13:07 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                    Heading
'Heading' må være inne <a> element

2024-04-15 13:07 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                    Heading
'Heading' må være inne <a> element

2024-04-15 13:07 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                    Heading
'Heading' må være inne <a> element

2024-04-15 13:07 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                    Heading
'Heading' må være inne <a> element

2024-04-15 13:08 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                Heading
'Heading' må være inne <a> element

2024-04-15 13:08 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                Heading
'Heading' må være inne <a> element

2024-04-15 13:08 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +            Heading
'Heading' må være inne <a> element

2024-04-15 13:08 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                    Heading
'Heading' må være inne <a> element

2024-04-15 13:08 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                  Heading
'Heading' må være inne <a> element

2024-04-15 13:08 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                Heading
'Heading' må være inne <a> element

2024-04-15 13:08 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                Heading
'Heading' må være inne <a> element

2024-04-15 13:09 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                Heading
'Heading' må være inne <a> element

2024-04-15 13:09 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                Heading
'Heading' må være inne <a> element

2024-04-15 13:09 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                Heading
'Heading' må være inne <a> element

2024-04-15 13:09 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.html
> +                Heading
'Heading' må være inne <a> element

2024-04-15 13:11 UTC, cristain7 requested changes
Hva om landscape card? Det trenger samme løsning

2024-04-17 08:23 UTC, cristain7 approved these changes

2024-04-24 11:56 UTC, cristain7 submitted a review, later dismissed

2024-05-06 17:54 UTC, larsboldt requested changes

2024-05-06 17:54 UTC, larsboldt commented on .stylelintrc.json
> +    "declaration-block-no-redundant-longhand-properties": null
Trodde vi unngikk å ha dette unntaket ved å konvertere til shorthand?

2024-05-07 16:27 UTC, larsboldt approved these changes

2024-05-08 16:32 UTC, kbergha commented on .stylelintrc.json
> +    "declaration-block-no-redundant-longhand-properties": null
Greit å svare ut denne, ellers ser det ok2k ut.

2024-05-10 07:53 UTC, jonaashl commented on .stylelintrc.json
> +    "declaration-block-no-redundant-longhand-properties": null
Denne har vi fjernet igjen ja.

2024-05-13 09:14 UTC, cristain7 submitted a review, later dismissed

2024-05-13 11:40 UTC, jonaashl commented on src/components/cards/portrait_card/portrait_card.scss
> +    z-index: 2;
Siden vi må utvide en link knyttet til headeren over hele kortet fikk jeg problemer med at den linken la seg over __actions delen av cardet. Dette har jeg klart å fikse, faktisk. Den burde vært fjernet. Har gjort det nå.

2024-05-13 11:53 UTC, jonaashl commented on src/components/cards/portrait_card/portrait_card.scss
> +  &:focus-within:has(.ods-button:focus),
Problemet her er at vi ikke kan bruke focus-visible for outline på linken til cardet. dette krevde focus within, Focus within fører til at outline på selve kortet ikke blir borte når man fokuserer på elementet som er i __actions.
Har ikke klart å finne en annen løsning på dette. Tips?

2024-05-13 12:17 UTC, jonaashl commented on src/components/cards/portrait_card/portrait_card.scss
> +  &:focus-within:has(.ods-button:focus),
omg jeg klarte å fikse det!!

2024-05-13 12:17 UTC, jonaashl commented on src/components/cards/portrait_card/portrait_card.scss
> +    z-index: 2;
fixed

2024-05-13 12:27 UTC, cristain7 approved these changes

2024-05-13 14:17 UTC, kbergha approved these changes

2024-05-14 07:21 UTC, larsboldt approved these changes

2024-05-14 07:26 UTC, merged