IO-452: Reactivity mapdata
oslokommune/ukeweb_designsystem pull request #497
Opened 2024-03-18 08:39 UTC by jonaashl

Flyttet fetching ut av komponenten
Gjort endringer på håndteringen av data.
GeoJson er nå object.
Skal ha fikset flere popups som legger seg på hverandre ved load.

(Ikke helt fornøyd med koden og tar gjerne feedback på ting som kan gjøres bedre)

2024-03-20 07:59 UTC, kbergha reviewed
Trur du kan vise dette for oss. litt vanskelig å bare se på koden.

2024-04-23 09:58 UTC, cristain7 commented on src/components/map/map.html
> +    document.addEventListener('DOMContentLoaded', () => {
Spacing er feil

2024-04-23 11:06 UTC, cristain7 commented on src/components/map/map.vue
> +        if (this.pointsGeoJson && this.pointsGeoJson.features && this.pointsGeoJson.features.length > 0) {
Optional chaining vil gjør det enkel:
if (this.pointsGeoJson?.features?.length > 0)

2024-04-23 11:28 UTC, cristain7 commented on src/components/map/map.vue
> +        this.lastDisplayedPopup = null;
Hva er dette for?

2024-05-07 09:58 UTC, larsboldt requested changes

2024-05-07 09:58 UTC, larsboldt commented on src/components/map/geoJsonUtils.js
> +  try {
hvorfor catche og kaste den videre som eneste handling, da kan man like godt ikke?

2024-05-14 11:35 UTC, cristain7 submitted a review, later dismissed

2024-05-22 09:59 UTC, kbergha approved these changes

2024-05-22 10:01 UTC, cristain7 approved these changes

2024-05-23 07:19 UTC, larsboldt approved these changes

2024-05-23 07:21 UTC, merged