Io 1240 Fix npm warnings
oslokommune/ukeweb_designsystem pull request #505
Opened 2024-04-25 11:52 UTC by cristain7

- add config files to .gitignore
- remove old styleguide files

2024-04-25 13:23 UTC, kbergha commented on .gitignore
> +.editorconfig
Eh... Disse fire skal vel alle være i Git?

2024-04-26 06:58 UTC, larsboldt requested changes

2024-04-26 06:58 UTC, larsboldt commented on .gitignore
> +.editorconfig
Ja disse må ikke ignoreres

2024-04-26 06:58 UTC, larsboldt commented on src/osg.js
Hva har dette med npm warnings å gjøre?

2024-04-26 06:58 UTC, larsboldt commented on src/osg.scss
Hva har dette med npm warnings å gjøre?

2024-04-26 07:31 UTC, cristain7 commented on src/osg.js
dette var i Checklist av saken som tillegg

2024-04-26 07:31 UTC, cristain7 commented on src/osg.scss
dette var i Checklist av saken som tillegg

2024-04-26 09:01 UTC, kbergha commented on .gitignore
> +.editorconfig
.eslintrc.json
.stylelintrc.json
svgo.config.js

Ingen av disse skal være i ignore.

2024-04-26 09:24 UTC, larsboldt requested changes

2024-04-26 09:24 UTC, larsboldt commented on .gitignore
> +.eslintrc.json
why should this be ignored by git?

2024-04-26 09:24 UTC, larsboldt commented on .gitignore
> +.stylelintrc.json
why should this be ignored by git?

2024-04-26 09:24 UTC, larsboldt commented on .gitignore
> +svgo.config.js
why should this be ignored by git?

2024-04-29 09:47 UTC, cristain7 commented on .gitignore
> +.editorconfig
jeg brukte feil fil, jeg mente å bruke .npmignore ikke .gitignore 🤦‍♀️

2024-04-30 13:31 UTC, larsboldt approved these changes

2024-04-30 17:53 UTC, kbergha approved these changes

2024-05-02 07:23 UTC, merged