Io 1080: Refactor animation css of accordion component to a helper
oslokommune/ukeweb_designsystem pull request #506
Opened 2024-05-02 13:35 UTC by cristain7

2024-05-06 17:57 UTC, larsboldt requested changes

2024-05-06 17:57 UTC, larsboldt commented on src/general/helpers/animations/animations.scss
> +.ods-animations {
Singular, ods-animation

2024-05-06 17:57 UTC, larsboldt commented on src/general/_index.scss
> +@use "helpers/animations/animations";
Singular, animation

2024-05-07 09:47 UTC, larsboldt submitted a review, later dismissed

2024-05-07 10:05 UTC, kbergha submitted a review, later dismissed

2024-05-07 10:14 UTC, kbergha approved these changes

2024-05-07 10:25 UTC, larsboldt approved these changes

2024-05-07 10:38 UTC, merged