IO-1022: Add outline on keyboard navigation
oslokommune/ukeweb_designsystem pull request #508
Opened 2024-05-10 07:35 UTC by jonaashl

2024-05-14 11:59 UTC, larsboldt requested changes

2024-05-14 11:59 UTC, larsboldt commented on src/components/form/input/input.scss
> +
Trenger vi denne ekstra linjen?

2024-05-14 11:59 UTC, larsboldt commented on src/components/form/radio/radio.scss
> +
extra line?

2024-05-14 11:59 UTC, larsboldt commented on src/components/links/link/link.scss
> +
extra line?

2024-05-14 12:06 UTC, cristain7 commented on src/components/accordion/accordion.scss
> +      outline: 0.25rem solid colors.$purple-light;
Denne koden gjentas 19 ganger i denne review. Vi snakket om dette tidligere, for å bruke en mixin fordi verdiene av box-shadow endres. Men jeg ser nå er det bare 2 unntak på denne regelen, Date og Radio. 
Jeg tror dette bør bruke en extend og hardkode date og radio. Tenker?

2024-05-14 13:40 UTC, jonaashl commented on src/components/accordion/accordion.scss
> +      outline: 0.25rem solid colors.$purple-light;
Og alt med border (button, checkbox, input, square, inline, search_season, select, pagination etc.)

2024-05-14 13:45 UTC, jonaashl commented on src/components/accordion/accordion.scss
> +      outline: 0.25rem solid colors.$purple-light;
Men jeg er enig, hadde vært bedre om vi kunne funnet en mixin-løsning.

2024-05-14 13:50 UTC, cristain7 commented on src/components/accordion/accordion.scss
> +      outline: 0.25rem solid colors.$purple-light;
Vanskelig å finne en felles løsning for border, de skifter farge men har samme størrelse 
(border: 0.125rem solid)
Det blir masse search-replace hvis verdier endrer her, men foreløpig har jeg ikke en bedre idé.

2024-05-15 07:52 UTC, cristain7 commented on src/components/form/input/input.scss
>    }
Denne kan være del av mixins.form-states

2024-05-15 07:53 UTC, cristain7 commented on src/components/form/select/select.scss
> +      }
Denne kan være del av mixins.form-states

2024-05-15 09:00 UTC, larsboldt commented on src/components/cards/status_card/status_card.html
> +              <a class="ods-status-card__link" href="javascript:void(0)">Heading</a>
Dette er ikke i testmiljøet. Er det riktig at man endrer fra hele card som klikkbart til kun heading?

2024-05-21 12:25 UTC, kbergha approved these changes

2024-05-21 12:36 UTC, jonaashl commented
> Lag et eller annet card i backlog på å se om man kan tørke opp (DRY) alle disse boxshadow/outline-definisjonene? Har allerede blitt kommentert litt av Cristina. Ellers ser det jo greit ut så vidt jeg kan se.

Har laget et card på å vurdere mixin for outlines. Det er den beste måten å gjøre det på, men tror det samtidig er lurt å rydde litt opp i stilingen slik at mixins kan brukes på flere komponenter. Det blir fort kluss hvis mixins funker på noe men ikke på alt.

2024-05-21 12:51 UTC, cristain7 approved these changes

2024-05-21 13:19 UTC, merged